name: Quran Bot Hourly Posts

on:
  schedule:
    # Run every hour at minute 0 (e.g., 1:00, 2:00, 3:00, etc.)
    - cron: '0 * * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  post-verse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests
        
    - name: Run Quran Bot
      env:
        TWITTER_API_KEY: ${{ secrets.API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: |
        python bot.py
        
    - name: Commit and push state file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add quran_bot_state.json
        git diff --staged --quiet || git commit -m "Update bot state after posting verse"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
